// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jim-ww/nms-go/internal/features/auth/role"
)

type Note struct {
	ID      uuid.UUID
	Title   string
	Content sql.NullString
	UserID  uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	Role      role.Role
	CreatedAt time.Time
	UpdatedAt time.Time
}
