// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type User struct {
	ID        string
	Username  interface{}
	Email     interface{}
	Password  interface{}
	Role      interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}
