// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package repository

import (
	"context"
)

const findAllNotes = `-- name: FindAllNotes :many
SELECT id, title, content, user_id, created_at, updated_at FROM notes
`

func (q *Queries) FindAllNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, findAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
